#!/bin/sh
# ========================================================
# Set the Time Zone
# ========================================================
TIMEZONE='CST6CDT,M4.1.0,M10.5.0'
ZONENAME='America/Mexico City'
echo 'Setting timezone to' $TIMEZONE
uci set system.@system[0].timezone="$TIMEZONE"
echo 'Setting zone name to' $ZONENAME 
uci set system.@system[0].zonename="$ZONENAME"

# ========================================================
# To identify better when connected to SSH and when seen on the network
# ========================================================
uci set system.@system[0].hostname='Terracotta'
uci set network.lan.hostname="`uci get system.@system[0].hostname`"
echo $(uci get system.@system[0].hostname) > /proc/sys/kernel/hostname

# ========================================================
# LAN config
# ========================================================
uci del network.lan.ipaddr
uci set network.lan.ipaddr='192.168.40.1'
uci set dhcp.lan.start='20'
uci set dhcp.lan.limit='200'

# ========================================================
# System Log
# ========================================================
uci set system.@system[0].log_size='512'
uci set system.@system[0].log_ip='127.0.0.1'
uci set system.@system[0].log_proto='tcp'
uci set system.@system[0].log_file='/root/system.log'
uci set system.@system[0].conloglevel='8'
uci set system.@system[0].cronloglevel='5'
uci commit system

# ========================================================
# Default theme
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci
# ========================================================

# ========================================================
# Commit changes, flush
# ========================================================
uci commit
sync

# ========================================================
# Flush LuCI cache
# ========================================================
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

# ========================================================
# Private Settings
# ========================================================
my_device='/dev/sda1'
my_dir='/mnt/share'
my_script="${my_dir}/init.sh"
if [ -b "${my_device}" ];then
    mkdir ${my_dir}
    mount ${my_device} ${my_dir}
    [ -f "${my_script}" ] && sh ${my_script}
fi

exit 0
